### ISSUE TITLE
Tabbing to year of military service doesn't work

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/vets-website#3421] opened 2016-10-17 18:19 UTC
Entering this on behalf of Stephanie:

Unable to tab into the year box on the military service screen.

Environment: 

IE11 (VA)

**Comment by akainic** [comment] 2016-10-18 13:37
I can't recreate this. Is this for the graduation year input at the very top of the screen or for the year input for enter or exit dates? Either way tabbing to it works for me, though I will say our tabbing is a bit messed up in general (if you previously tabbed to the Submit button, it will stay on the button once you get to the next screen, making it hard to tab up to the first question).

**Comment by plusjeff** [comment] 2016-10-18 14:42
@akainic : When Stephanie showed me, it was happening to her on both. Have you tried it with IE 11?

**Comment by plusjeff** [comment] 2016-10-18 14:43
If this is helpful, you can get IE 11 running on your Mac using these free Microsoft VMs:

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by jbalboni** [comment] 2016-10-25 19:55
I can't reproduce this on IE11.

**Comment by akainic** [comment] 2016-10-31 21:28
Closing as we can't reproduce

**Closed** 2016-10-31 21:28 UTC
Labels: bug, edu-benefits
