### ISSUE TITLE
Health care application is broken in Internet Explorer 11

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3725] opened 2016-11-04 00:15 UTC
The verify-and-submit page is broken. You can't click each panel opened and closed. Developer tools throws a bunch of XML errors. Possibly related to department-of-veterans-affairs/messaging-fe#146 and use of `Object.assign` (which we do not polyfill and IE does not support). Possibly not.

If it is caused by `Object.assign`, we can either use [lodash's assign](https://lodash.com/docs/4.16.6#assign) method or add a polyfill.

**Comment by jcmeloni** [comment] 2016-12-06 18:32
@akainic Confirmed still an issue.

**Comment by akainic** [comment] 2016-12-06 18:58
Thanks for the ping on this @jcmeloni. Added the right label so it gets tracked in our Waffle board. Perhaps something @jbalboni could take a look at?

**Comment by jbalboni** [comment] 2016-12-06 19:34
Yeah, I can take a look. We should be polyfilling Object.assign, though. Maybe it's not imported correctly.

**Comment by jbalboni** [comment] 2016-12-06 19:51
@jcmeloni How did you confirm this was still an issue? I've pulled hca up in IE11 on production and locally and don't see any errors on the review page. It might be data specific, so screenshots or what steps you took would be helpful. (cc @webinista)

**Comment by jcmeloni** [comment] 2016-12-06 20:18
@jbalboni I loaded it in IE11 and ran through the app on production and while there are no longer XML errors, the note that "You can't click each panel opened and closed" from the original report is still true.

**Comment by jbalboni** [comment] 2016-12-06 20:58
@jcmeloni On HCA, there are Edit/Next buttons that let you move between panels. Are those what you clicked on? The gray boxes with the title of each section don't open or close the panels (which is confusing).

**Comment by jcmeloni** [comment] 2016-12-06 21:00
@jbalboni The edit/next buttons work (yay) but there is no concept of close/open panels which is what I thought was originally being referenced since we have that pattern elsewhere.

Up to you if you close it as by design or not -- I'm just trying to keep things organized if there IS an issue to work on. :)

**Comment by jbalboni** [comment] 2016-12-06 21:09
Cool. I think this is working as designed, then. We are planning on migrating HCA to the same review page design as the new education form, which does follow that accordion pattern, but I think that's tracked in another issue. We can close this.

**Closed by jbalboni** 2016-12-06 21:09 UTC
Labels: bug, front end, hca, health-application
