### ISSUE TITLE
Sticky box is jumping

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3837] opened 2016-11-08 22:15 UTC
The sticky grey box with green form button jump when i scroll on mobile. @akainic could you label the priority? Can't gauge if this is hi-pri.

**Comment by jbalboni** [comment] 2016-11-29 16:10
Going to close this, as it's a duplicate of #3827.

**Closed by jbalboni** 2016-11-29 16:10 UTC
Labels: 1-current-sprint, bug, edu-benefits, low-priority
