### ISSUE TITLE
User voice link discrepancy between vets-website and

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1405] opened 2016-03-14 14:27 UTC
Vets-website has the new design hotness for the user voice logo
![screen shot 2016-03-14 at 10 23 07 am](https://cloud.githubusercontent.com/assets/1307774/13747491/d69ba0a2-e9ce-11e5-98e5-1001fde8c6e9.png)

and all the old repos have the desired functionality
![screen shot 2016-03-14 at 10 23 02 am](https://cloud.githubusercontent.com/assets/1307774/13747490/d690eae0-e9ce-11e5-83bf-4c8bcf909d83.png)

make a consistent combination with both. Thoughs, @gnakm ? I think we basically need to have space for 1) opening the box for feedback 2) sending people to the page.

Functionality of the pop up window remains the same for both, from what I can tell.

**Comment by emilyville** [comment] 2016-03-16 18:47
Like so?

![screen shot 2016-03-16 at 2 47 09 pm](https://cloud.githubusercontent.com/assets/1307774/13824792/026ed90c-eb86-11e5-8e5d-d0dfffaefc04.png)

**Comment by gnakm** [comment] 2016-03-16 18:57
LGTM! @emilyville

**Comment by koconnor719** [comment] 2016-03-29 17:33
@webinista tiffany this issue is not closed.  can you pls check w/ me before closing:)  the feedback forum is now showing up as 2 links on the homepage (but still the old version--which is the one we wanted based on Veteran feedback on the VEC page). see the 2 different displays below. i'm not sure what research is informing the new format and 2 links now on the homepage.  i talked w/ mary ann and she's not aware of any data to support this.  can we pls. go back to the way the feedback forum was before it got changed for some reason?  (i think Danny made a change about 3 sprints ago??)

Homepage:
<img width="646" alt="screen shot 2016-03-29 at 1 31 20 pm" src="https://cloud.githubusercontent.com/assets/13770771/14117413/92df56e8-f5b2-11e5-8dff-d7551de42164.png">

VEC page
<img width="1060" alt="screen shot 2016-03-29 at 1 31 53 pm" src="https://cloud.githubusercontent.com/assets/13770771/14117427/a2d414c6-f5b2-11e5-9a9c-b5803dc0b16b.png">

**Comment by webinista** [comment] 2016-03-29 17:48
@koconnor719 I closed this issue because the task is complete and merged into master. It just isn't deployed everywhere. I did not close #1305 because there is still a discrepancy. For task management and tracking, let's please close one :-)

**Comment by koconnor719** [comment] 2016-03-29 17:51
ok sorry--i saw a change that actually had deployed (new this week)?  so i thought that it DID deploy already:)  sorry about that.  which one would you like to close?  i can do that now.

**Comment by koconnor719** [comment] 2016-03-29 17:52
it seems to be changing every week to something different?  is someone driving these changes?

**Closed** 2016-03-29 17:52 UTC
Labels: design

**Comment by koconnor719** [comment] 2016-03-29 20:23
talked to emily confirmed this is closed.
