### ISSUE TITLE
Applications header thinks you're still signed in after signing out

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#4046] opened 2016-11-19 01:17 UTC
When the user has signed in, then signed out, then goes to an application landing page (such as https://staging.vets.gov/disability-benefits/track-claims/your-claims), the Sign in button pops up successfully whereas the header still says "Hello, |Profile|Sign Out".  This is happening across applications (Claims, Rx, and SM all have the same issue). 

<img width="1180" alt="screen shot 2016-11-18 at 8 17 55 pm" src="https://cloud.githubusercontent.com/assets/4719765/20451822/1f67706a-adcc-11e6-915a-f64bf601633b.png">

Looking around more, this also happens when going to non-react pages too. For example, here is the homepage after signing out (as you can see the user's email address has been removed after "hello", but it doesn't go back to saying "sign in | register" in the header. 

<img width="1183" alt="screen shot 2016-11-18 at 8 15 58 pm" src="https://cloud.githubusercontent.com/assets/4719765/20451805/d73e1e06-adcb-11e6-9846-5d53df16005d.png">

**Comment by crwallace** [comment] 2016-11-21 14:54
this is a duplicate of #3954

**Comment by crwallace** [comment] 2016-11-21 16:30
This was resolved by SLO implementation.

**Closed** 2016-11-21 16:30 UTC
Labels: Identity, vanguard
