### ISSUE TITLE
Develop content to inform users of any scheduled maintenance windows or anticipated downtime of back end system - must happen before launch

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#3578] opened 2016-10-27 23:31 UTC
pre-launch for education benefits: https://github.com/department-of-veterans-affairs/edu-benefits-team/blob/master/project-management-and-charter-doc/checklist.md

**Comment by akainic** [comment] 2016-11-02 13:35
Duplicate of https://github.com/department-of-veterans-affairs/edu-benefits-team/issues/101. Closing this one.

**Closed by akainic** 2016-11-02 13:35 UTC
Labels: 1-current-sprint, edu-benefits
