### ISSUE TITLE
Continue loads new form but doesn’t scroll to the top

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#3073] opened 2016-09-14 21:59 UTC
When you click continue to go to the next part of the form. The page stays at its current scroll position. This means you frequently have to scroll back to the top of the screen to fill out the next field. As far as I can tell this is on all screens.

**Comment by goldenmeanie** [comment] 2016-09-15 14:41
Might be a duplicate of [Add scrolling](https://github.com/department-of-veterans-affairs/vets-website/issues/2925)

**Comment by akainic** [comment] 2016-09-21 11:51
Yes, this is a duplicate of the other ticket. Closing this one and keeping the other open.

**Closed by akainic** 2016-09-21 11:51 UTC
Labels: edu-benefits, front end
