### ISSUE TITLE
Piano Keys missing from some pages

### ISSUE THREAD

**Issue by recorr** [department-of-veterans-affairs/vets-website#3962] opened 2016-11-15 02:21 UTC
I found three issues in the audit of the vets.gov and corresponding va.gov pages. These three issues are on vets.gov.

1. This page:
https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/

Is missing links to these pages:
http://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/
http://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/asbestos/
http://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/birth-defects/
http://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/contaminated-drinking-water-at-camp-lejeune/
http://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/gulf-war-illness/
http://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/ionizing-radiation/
http://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/mustard-gas/
http://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/project112-SHAD/
http://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/radiogenic-risk-activities/
http://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/specific-environmental-hazards/

2. There appears to be no on-page navigation to reach this page:
http://www.vets.gov/disability-benefits/conditions/service-connected/

3. This page:
http://www.vets.gov/disability-benefits/conditions/special-claims/

Is missing links to these pages:
http://www.vets.gov/disability-benefits/conditions/special-claims/automobile/
http://www.vets.gov/disability-benefits/conditions/special-claims/clothing/
http://www.vets.gov/disability-benefits/conditions/special-claims/clothing/
http://www.vets.gov/disability-benefits/conditions/special-claims/dentistry/
http://www.vets.gov/disability-benefits/conditions/special-claims/hospitalization/
http://www.vets.gov/disability-benefits/conditions/special-claims/individual-unemployability/
http://www.vets.gov/disability-benefits/conditions/special-claims/prestabilization/
http://www.vets.gov/disability-benefits/conditions/special-claims/title-38-USC-1151/

Thanks,

-Ken

**Comment by bethpotts** [comment] 2016-11-15 21:58
@dannychapman @rroueche This is a blocker as far as SMEs being able to click around in the Disability plain language branch starting EOD tomorrow (Wednesday). Can we get some help resolving this?

**Comment by dannychapman** [comment] 2016-11-16 01:13
Taking a look see now.

**Comment by dannychapman** [comment] 2016-11-16 01:34
@bethpotts Fixed on disability-plain-language branch. Building now. @rroueche let's review this tomorrow.

**Comment by bethpotts** [comment] 2016-11-16 03:33
@dannychapman @recorr Thanks, Danny! Looks good on the disability-plain-language-update branch now! The same problem is on production too. I mention that because this branch won't push to production for 1-2 weeks, depending on what feedback we get from SMEs.

**Comment by dannychapman** [comment] 2016-11-16 18:28
@recorr Question - for 2, where should that be linked from?

**Comment by recorr** [comment] 2016-11-16 18:57
@dannychapman I believe is should be a piano key on the following page:

https://www.vets.gov/disability-benefits/conditions/

**Comment by melwoodard** [comment] 2016-11-16 20:11
FYI, I think this was caused by a change made to the employment page - https://www.vets.gov/employment/

It intentionally uses a different style for the bottom links instead of piano keys. @dannychapman can you make sure employment isn't affected by the changes to the other pages?

**Comment by dannychapman** [comment] 2016-11-17 22:06
@melwoodard Not seeing any issues with Employment, also been fixed by #4001. This is fixed on staging, so closing.

**Closed by dannychapman** 2016-11-17 22:06 UTC
