### ISSUE TITLE
UserVoice Idea: Employment Profile - Information Block Removal

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#938] opened 2015-12-23 17:29 UTC
Currently there is no way to delete a reference block. There needs to be a way to remove references and other information blocks from the resume without deleting the entire thing and starting over.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11187252-employment-profile-information-block-removal

**Comment by koconnor719** [comment] 2015-12-29 15:13
alex, can you test this and let me know response?  i'm thinking this is a future enhancement?

**Comment by MarinaMartin** [comment] 2015-12-29 22:16
This is a dupe of issue #304 in the VEC repo.

**Comment by ayaleloehr** [comment] 2015-12-30 02:13
@koconnor719 as Marina said, This is a dupe of:

https://github.com/department-of-veterans-affairs/veterans-employment-center/issues/304

(I pasted that link here because Marina's comment auto-linked to issue 304 in this repo, which seemed potentially confusing and I want to make sure we at least have the right link here somewhere).

So I think a comment saying that we agree that's an important feature, we plan to implement it, the site is a work in progress, check back soon, etc. would be the right approach.

**Comment by MarinaMartin** [comment] 2015-12-30 02:35
Would be cool if we put a note about this in the VEC issue, so when we do implement it, we can update the UserVoice comment then too.

**Comment by koconnor719** [comment] 2015-12-30 02:49
posted response; leaving this issue open so i can update the response when #304 is completed;

Thank you for your feedback. We agree! This is an important feature, and our team is working on it.  It will take us a few weeks to do this, so please check back in early 2016.  

vets.gov team

**Comment by ayaleloehr** [comment] 2016-04-15 20:50
@koconnor719 This is live in production if we still want to update this UserVoice comment. Please close once if do.

**Comment by koconnor719** [comment] 2016-05-05 02:10
posted and closed:

Thank you for your feedback.  This issue has been fixed!

vets.gov team

**Closed by koconnor719** 2016-05-05 02:10 UTC
Labels: enhancement, User voice - VEC, UserVoice
