### ISSUE TITLE
Set 'begin training' date range based on 'election date'

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3791] opened 2016-11-07 18:37 UTC
2) If possible (I know this is a future release), could we get some sort of warning if they enter a begin training date that is BEFORE the date they have entered as their election date?

**Comment by cweber** [comment] 2016-11-07 18:55
That makes sense and is a complex field validation that is probably worth it since it is likely to catch logic problems related to the complexity of benefits, not just typos.

But agreed that we can add that after launch.

**Comment by cweber** [comment] 2016-12-08 21:12
@jbalboni Did this get taken care of during all of the date updates?

**Comment by jbalboni** [comment] 2016-12-09 12:55
@cweber No, not yet, though I did see the note on the other issue (which is still in progress).

**Comment by cweber** [comment] 2016-12-09 13:34
No rush. I was just cruising issues I'd started and figured this was a candidate for having been done, but not closed.

**Comment by leannammiller** [comment] 2016-12-09 15:09
@jbalboni confirming that this will be taken care of in the other issue - can we close this one?

**Comment by leannammiller** [comment] 2016-12-16 15:57
@jbalboni confirming that this will be taken care of in the other issue - can we close this one?

**Comment by jbalboni** [comment] 2016-12-16 16:39
@leannammiller No, this is still valid. It was mentioned in another issue, but I left it out of that one because the changes were already complicated.

**Comment by rtluu** [comment] 2017-08-31 16:51
unclear what the issue is here and we haven't had any recent validation issues from education. closing

**Closed by rtluu** 2017-08-31 16:51 UTC
Labels: ed benefits, enhancement, front end, rainbows
