### ISSUE TITLE
Refreshing page in HCA returns GET error

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#2800] opened 2016-08-19 13:45 UTC
If at a url within the app (e.g., http://localhost:3000/healthcare/apply/application/veteran-information/personal-information), if you refresh the page you get an error.

<img width="740" alt="screen shot 2016-08-19 at 9 44 05 am" src="https://cloud.githubusercontent.com/assets/3886085/17811635/965adcd4-65f1-11e6-9212-19cab869ca1b.png">

**Comment by akainic** [comment] 2016-08-19 14:12
From Albert: 
That's supposed to be handled by the historyapifallback option in webpack....
The reason you get a 404 is because no file exists at that URL... But the webserver is supposed to be configured to always return the same html for healthcare/apply/application

**Comment by webinista** [comment] 2016-08-19 16:21
We can probably close this as a duplicate of #2780.

**Closed** 2016-12-06 17:15 UTC
