### ISSUE TITLE
address validation error street length over maximum

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/vets-website#4711] opened 2017-01-18 23:43 UTC
```
Form The property '#/veteranAddress/street' was not of a maximum string length of 50 in schema efb95931-f477-5756-8e16-ed95db359c86#
```
happened on Jan 11, 2017 1:05:29 AM UTC

**Comment by annekainicUSDS** [comment] 2017-01-23 15:20
Double check validations to make sure we are validating the street address to not be blank.

**Comment by cagedcrown** [comment] 2017-01-26 21:21
I am unable to replicate this error locally. There is also a character limit of 30 for the street address. 

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/js/common/components/questions/Address.jsx#L111

**Comment by leannammiller** [comment] 2017-01-26 21:32
@jbalboni @annekainicUSDS - Mo is blocked on this?

**Comment by jbalboni** [comment] 2017-01-27 19:34
@leannammiller I think we can close this. Mo and I can't reproduce it and we haven't seen any more.

**Comment by leannammiller** [comment] 2017-01-30 13:24
ok

**Closed by leannammiller** 2017-01-30 13:24 UTC
Labels: ed benefits, front end, in progress, rainbows
