### ISSUE TITLE
User Voice -not sending responses

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#1030] opened 2016-01-12 21:21 UTC
User voice is not sending vets.gov admin posted responses to feedback back to original posters; i believe it is supposed to do this??? so people who submit feedback aren't getting our responses--unless they come back to the site. @emilyville

**Comment by MarinaMartin** [comment] 2016-01-13 03:35
@emilyville was researching this, I am assigning it to her (Emily, assign back to me if you need to!)

**Comment by emilyville** [comment] 2016-01-13 12:31
@koconnor719 this is a duplicate of #1020 and that issue has how we can fix it. Closing this issue - I will assign that one to you.

**Closed by emilyville** 2016-01-13 12:31 UTC
Labels: bug
