### ISSUE TITLE
Consolidate validations

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#4179] opened 2016-12-01 15:23 UTC
Right now we have duplication validation functions in each of our `validations.js` files within `common/utils/`, 'hca/utils', and 'edu-benefits/utils'. As soon as they get out of sync it has the potential to create issues. 

We should try to include as many of the validation functions in `common/utils` as possible, and only put ones that are truly unique in the project-specific validation files. Then we should import the common ones into the project-specific ones as needed.

**Comment by alexose** [comment] 2016-12-01 18:58
Yes, this should definitely be fixed.  A good first pass might be to [look for duplicate code](https://github.com/danielstjules/jsinspect) and consolidate accordingly.

**Comment by jbalboni** [comment] 2016-12-01 19:05
This is sort of a duplicate of #3012. 

Another thing to think about here is that the way we handle validation specific messages is also awkward and it'd probably be good to figure out a better solution for that.

**Comment by akainic** [comment] 2016-12-01 19:09
@jbalboni yes it is! Sorry about that. We can close one or the other. I'll close this one in favor of #3012.

**Closed** 2016-12-01 19:10 UTC
Labels: edu-benefits, health-application
