### ISSUE TITLE
search is missing from GI tool and FL; "feedback forum" missing from GI

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#936] opened 2015-12-23 05:16 UTC
the header search bar is missing from GI tool and FL tool pages--but it is on the VEC pages.  is there a reason the headers are different?

![screen shot 2015-12-23 at 12 17 20 am](https://cloud.githubusercontent.com/assets/13770771/11971372/8e2ba254-a90a-11e5-8902-aabc41af2bb0.png)

also at the bottom of page, "feedback forum" is missing from GI tool, but it is on the FL and VEC pages.

![screen shot 2015-12-23 at 12 16 04 am](https://cloud.githubusercontent.com/assets/13770771/11971363/6010e1c2-a90a-11e5-9900-e93787080881.png)

**Comment by dannychapman** [comment] 2015-12-31 16:15
@koconnor719 This is by design for now, as it is confusing to have the global vets.gov search within an app. Closing, but we should continue to iterate on this.

**Closed by dannychapman** 2015-12-31 16:15 UTC
Labels: design, question
