### ISSUE TITLE
validation error, all fields are objects

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/vets-website#4107] opened 2016-11-25 18:56 UTC
this validation error happened once on Nov 25, 2016 2:14:36 AM UTC. all values were in the form {"value"=>"foo", "dirty"=>true}

Form The property '#/' contains additional properties ["checkedBenefit", "seniorRotcCommissioned", "activeDutyRepaying", "hasNonMilitaryJobs", "emailConfirmation"] outside of the schema when none are allowed in schema 6d3ac55d-0966-5868-be2d-0f1191776ce9, Form The property '#/benefitsRelinquished' of type Hash did not match the following type: string in schema 6d3ac55d-0966-5868-be2d-0f1191776ce9, Form The property '#/benefitsRelinquished' value {"value"=>"unknown", "dirty"=>true} did not match one of the following values: chapter1607, unknown, chapter30, chapter1606 in schema 6d3ac55d-0966-5868-be2d-0f1191776ce9, Form The property '#/veteranFullName/first' of type Hash did not match the following type: string in schema 6d3ac55d-0966-5868-be2d-0f1191776ce9#, Form The property '#/veteranFullName/middle' of type Hash did not match the following type: string in schema 6d3ac55d-0966-5868-be2d-0f1191776ce9#, Form The property '#/veteranFullName/last' of type Hash did not match the following type: string in schema 6d3ac55d-0966-5868-be2d-0f1191776ce9#, Form The property '#/veteranFullName/suffix' value {"value"=>"", "dirty"=>false} did not match one of the following values: Jr., Sr., II, III, IV in schema 6d3ac55d-0966-5868-be2d-0f1191776ce9#, Form The property '#/gender' of type Hash did not match the following type: string in schema 6d3ac55d-0966-5868-be2d-0f1191776ce9, Form The property '#/gender' value {"value"=>"M", "dirty"=>true} did not match one of the following values: M, F in schema 6d3ac55d-0966-5868-be2d-0f1191776ce9, Form The property '#/veteranDateOfBirth' of type Hash did not match the following type: string in schema 6d3ac55d-0966-5868-be2d-0f1191776ce9#, Form The property '#/veteranSocialSecurityNumber' of type Hash did not match the following type: string in schema 6d3ac55d-0966-5868-be2d-0f1191776ce9#, Form The property '#/veteranAddress' of type Hash did not match any of the required schemas. The schema specific errors were:

- oneOf #0:
    - The property '#/veteranAddress/postalCode' of type Hash did not match the following type: string
    - The property '#/veteranAddress/state' value {"value"=>"FL", "dirty"=>true} did not match one of the following values: AB, BC, MB, NB, NF, NT, NV, NU, ON, PE, QC, SK, YT
    - The property '#/veteranAddress/country' value {"value"=>"USA", "dirty"=>false} did not match one of the following values: CAN
...etc

**Comment by jbalboni** [comment] 2016-11-29 18:58
Tried this in Opera 41, which was the UA associated with this error, haven't been able reproduce it so far. 

It looks like someone submitted an empty, unconverted form, but it's not clear how they could have gotten through the submit button being disabled and the conversion call that runs it through `JSON.stringify`.

**Comment by akainic** [comment] 2016-12-05 19:16
Cannot reproduce and have not seen it again since first occurring, closing for now.

**Closed by akainic** 2016-12-05 19:16 UTC
Labels: edu-benefits

**Comment by lihanli** [comment] 2016-12-08 00:29
this error happened again on Dec 7, 2016 4:08:00 PM UTC for someone using Safari
sentry error: http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/304/
