### ISSUE TITLE
Facility locator not showing results

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#3948] opened 2016-11-13 15:19 UTC
facility locator is not showing results correctly; when i search for 20001 (DC) it return no results:  

![screen shot 2016-11-13 at 10 03 27 am](https://cloud.githubusercontent.com/assets/13770771/20246699/aa7903f8-a98a-11e6-9d82-7ae10044794c.png)

**Comment by NatalieEMoore** [comment] 2016-11-13 15:52
This was on Safari.

**Comment by patrickvinograd** [comment] 2016-11-13 17:19
For log correlation screenshot timestamp is 2016-11-13 10:03:27 am

**Comment by patrickvinograd** [comment] 2016-11-13 21:13
This seems intermittent. When I see this on Chrome, sometimes I see map pointers flash onto the map very quickly and then disappear. I looked at the API requests using Chrome Developer Tools, and I sometimes see two API requests in rapid succession with different bounding boxes:
```
https://api.vets.gov/v0/facilities/va?bbox[]=-122.82371520996095&bbox[]=45.383983820995105&bbox[]=-122.46459960937501&bbox[]=45.646208310900626&page=1
https://api.vets.gov/v0/facilities/va?bbox[]=-122.670417&bbox[]=45.504776&bbox[]=-122.618885&bbox[]=45.52371&page=1
```
In this case the first request looks like the actual map display area and the response from API includes some facilities. The second request bounding box is a smaller subset of the map display area that doesn't include any facilities and so nothing is returned by the API and nothing is displayed. 
Also sometimes the two adjacent requests are both `GET`s, sometimes one is an `OPTIONS`.

**Comment by patrickvinograd** [comment] 2016-11-13 21:15
There is a second issue which is a devops issue - we are sometimes getting a 504 gateway timeout from the API requests during map refresh when doing a new search or panning/zooming. I think this is a reverse proxy issue that I will investigate separately.

**Comment by patrickvinograd** [comment] 2016-11-13 21:23
On dev I see the two API requests happening but they always have the same, accurate, bounding box.

**Comment by patrickvinograd** [comment] 2016-11-13 22:39
Panning/zooming results in multiple queries also, but with the same bounding box. Maybe it's an artifact of the search/geocoding mechanism that results in two API requests with different bounding boxes, maybe due to resetting the zoom level?

**Comment by bshyong** [comment] 2016-11-13 23:03
^ I will investigate this issue. Panning/zooming should definitely change the bounding box. The second request with a smaller box seems like a bug - perhaps something relating to the event listeners on the map handling a bounds/view change

**Comment by patrickvinograd** [comment] 2016-11-14 07:16
I've also seen a case where doing a page reload jumps to the location in the query params, but populates the facility list with Washington DC facilities from the default location - so it really seems like you're getting multiple asynchronous callbacks from API queries, but they're coming back out of order so they don't match up with the current map display.

**Comment by bshyong** [comment] 2016-11-14 16:44
@NatalieEMoore @koconnor719 for zipcode 20001 there are indeed no facilities in that zipcode. there are facilities right outside of that area, but 20001 covers a small area where no VA facilities are inside.

![screen shot 2016-11-14 at 8 38 29 am](https://cloud.githubusercontent.com/assets/303289/20273368/d2f166fc-aa45-11e6-9d36-2a703806861e.png)

We should discuss this in more depth @NatalieEMoore @crwallace @gnakm. It's not a bug, but it might be confusing to a user. One way to solve this is to institute a minimum size for the search area, i.e if the user searches 20001, we will actually search a larger area beyond 20001.

Also related—we should get our hands on analytics data for the queries that users are typing in to better inform our decision making. Are they primarily entering zipcodes, states, cities, addresses?

**Comment by gnakm** [comment] 2016-11-14 16:59
@bshyong Let's continue talking about this. I think that's why we should show both pin and highlight because if we do what you're suggesting (zoom at a larger area beyond the search), then users will know that it is beyond their search + know that there is still something near by. 

When I searched "20001" on desktop, chrome, I get this:
<img width="1003" alt="screen shot 2016-11-14 at 11 55 24 am" src="https://cloud.githubusercontent.com/assets/13420618/20274210/cd558554-aa61-11e6-8f31-aa608dfd3ea4.png">

but on android mobile, i get 0 results.

**Comment by bshyong** [comment] 2016-11-14 17:39
@gnakm Agree—we need to talk about this in more detail. I strongly suggest finding a solution that doesn't require boundary highlighting as it is a huge undertaking and may introduce more issues and UI cases to think about. Let's see if there are any quick wins we can do to make things more intuitive for the user.

For example, could we change the copy on the "no results" text? e.g. we could not find any facilities near 20001, please try zooming out or entering a different search area.

Or for example enforcing a large minimum size for the search area. This might not help if somebody is searching in a rural area, but it will eliminate many cases where the searched area is too small.

If we are able to get any visibility on the types of queries that we are seeing, that will help us figure out what direction we should be optimizing towards.

**Comment by koconnor719** [comment] 2016-11-14 17:46
@NatalieEMoore shouldn't it show the closest facilities?

**Comment by NatalieEMoore** [comment] 2016-11-14 18:20
@koconnor719 yes, we are going to hop on a call at 2 to figure out a plan!

**Comment by NatalieEMoore** [comment] 2016-11-15 19:45
@bshyong can this be closed since it is being discussed on a different issue?  We are changing it so that results will show if @koconnor719 were to enter that zip.  (10 closest facilities)

**Comment by bshyong** [comment] 2016-11-15 19:46
Yes, let's close it

Ben Shyong






On Tue, Nov 15, 2016 at 11:45 AM -0800, "Natalie Moore" <notifications@github.com> wrote:












@bshyong can this be closed since it is being discussed on a different issue?  We are changing it so that results will show if @koconnor719 were to enter that zip.  (10 closest facilities)

**Closed** 2016-11-15 19:47 UTC
Labels: bug, FL
