### ISSUE TITLE
Use a consistent style for secondary buttons

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2677] opened 2016-08-08 18:10 UTC

**Comment by melwoodard** [comment] 2016-08-11 18:30
We should be using the class `.usa-button-outline` seen here: https://standards.usa.gov/buttons/

**Comment by webinista** [comment] 2016-12-17 01:06
Is this a duplicate of #4332?

**Comment by melwoodard** [comment] 2016-12-17 04:50
I think we can tackle both issues in one. Closing this one.

**Closed by melwoodard** 2016-12-17 04:50 UTC
Labels: CSS, enhancement, vanguard
