### ISSUE TITLE
End date error happens prematurely

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/vets-website#3416] opened 2016-10-17 17:55 UTC
![image](https://cloud.githubusercontent.com/assets/950486/19448746/1b2921a2-9471-11e6-8b2f-7ab9012440fe.png)

Steps:
1. Get to the Military history page
2. Fill in State date for tour of duty
3. Fill in month and day for end date

Expected results:

No error message

Actual results:

Error message when tabbing into the year box

**Comment by akainic** [comment] 2016-10-18 13:46
Can't recreate

**Comment by J-Quag** [comment] 2016-10-26 13:04
I just tested this as well, seems fine... unless I click on the year box and tab out of it.

**Comment by jbalboni** [comment] 2016-11-02 12:20
@J-Quag That's the intended behavior. I'm closing this.

**Closed by jbalboni** 2016-11-02 12:20 UTC
Labels: bug, edu-benefits
