### ISSUE TITLE
double apply button

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#2434] opened 2016-05-31 17:38 UTC
https://www.vets.gov/education/work-learn/workstudy/

![screen shot 2016-05-31 at 10 37 38 am](https://cloud.githubusercontent.com/assets/1307774/15684391/c25d43d6-271b-11e6-8db4-8a52f6be18ca.png)

**Comment by webinista** [comment] 2016-05-31 22:12
Duplicate of #2430

**Closed by webinista** 2016-05-31 22:12 UTC
